version: '3'
services:
  iotai_train:
    build:
      context: .
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
      - /home:/home
    user: "1000:1000"
    image: "iotai_train_gpu:latest"
    