version: '3'
services:
  iotai_infer:
    build:
      context: .
    user: ${CURRENT_UID}
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
      - /home:/home
    ports:
      - "480:80"  # nginx 
    image: "iotai_infer_gpu:latest"
    